export const RESPONSE_CODES = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  ERROR: 400,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  METHOD_NOT_ALLOWED: 405,
  SERVER_ERROR: 500,
};

export const USER_ROLE = {
  ADME_ADMIN: 'ADMEADMIN',
  OWNER: 'OWNER',
  SALES_MANAGER: 'MANAGER',
  SALES_EXECUTIVE: 'EXECUTIVE',
};
